# Generated by Django 5.2.4 on 2026-02-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_boarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
