# Generated by Django 5.2.4 on 2026-02-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_boarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
