# Generated by Django 5.2.4 on 2026-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
