# Generated by Django 5.2.4 on 2026-02-21 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('custom_sections', models.JSONField(blank=True, default=list)),
                ('theme', models.CharField(default='Modern', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
