# Generated by Django 5.2.4 on 2026-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cvprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='custom_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
