# Generated by Django 5.2.4 on 2026-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cvprofile_custom_contacts_cvprofile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='education_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
