# Generated by Django 5.2.4 on 2026-02-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cvprofile_education_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
